// <auto-generated />
using System;
using DespesaViagem.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DespesaViagem.Infra.Migrations
{
    [DbContext(typeof(DespesaViagemContext))]
    partial class DespesaViagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DespesaViagem.Domain.Models.Core.Records.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Despesas.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoDespesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalDespesa")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Despesas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Viagens.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Adiantamento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoViagem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("MatriculaFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeViagem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StatusViagem")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar");

                    b.Property<decimal>("TotalDespesas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("Viagem", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Despesas.DespesaHospedagem", b =>
                {
                    b.HasBaseType("DespesaViagem.Domain.Models.Despesas.Despesa");

                    b.Property<int>("QuantidadeDias")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal");

                    b.ToTable("DespesaHospedagem", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Core.Records.Endereco", b =>
                {
                    b.HasOne("DespesaViagem.Domain.Models.Despesas.DespesaHospedagem", "DespesaHospedagem")
                        .WithOne("Endereco")
                        .HasForeignKey("DespesaViagem.Domain.Models.Core.Records.Endereco", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DespesaHospedagem");
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Despesas.Despesa", b =>
                {
                    b.HasOne("DespesaViagem.Domain.Models.Viagens.Viagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Despesas.DespesaHospedagem", b =>
                {
                    b.HasOne("DespesaViagem.Domain.Models.Despesas.Despesa", null)
                        .WithOne()
                        .HasForeignKey("DespesaViagem.Domain.Models.Despesas.DespesaHospedagem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespesaViagem.Domain.Models.Despesas.DespesaHospedagem", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
